### ISSUE TITLE
Author and paper metadata

### ISSUE THREAD

**Issue by blairlyons** [allen-cell-animated/simulariumio#34]
## Use Case
It would be nice to be able to save metadata like the publication and names of authors associated with the trajectory.

## Acceptance Criteria
A Python user can specify strings for author and publication metadata and have it saved in .simularium files

## Details
Add these metadata fields to the file format, and optionally output them in .simularium files. Include:
- Trajectory title
- Model info:
  - Model title
  - Authors
  - Publication DOI
  - Version
  - Description
  - Code URL
  - Code license URL
  - Model input data URL
  - Raw output data URL

Proposed additions to the file format are here https://docs.google.com/document/d/1hxRQ1quZecX3Lo7WEDLN-MPU1Ebiiv6f9WKMt8i_8ZE/edit?usp=sharing

**Comment by schoinh** [comment]
I just noticed the "Model info" doesn't include publication title/year/journal name, are we thinking we should try to get that with the DOI through some kind of lookup service?

**Comment by blairlyons** [comment]
yes that's what I was thinking, it would be redundant

**Comment by schoinh** [comment]
Note to self: 

Could use this API for DOI lookups, but not sure yet the scope of Crossref, i.e. if they would have the papers we need 100% of the time. https://api.crossref.org/swagger-ui/index.html 

There's also this package we could install, but not sure yet which lookup service/database they use https://www.npmjs.com/package/citation-js

**Comment by schoinh** [comment]
Tested out the Crossref API with a few of our posted models' DOIs, looks like we can get all the info we need for them. I'm still not sure about:
* What to do if we can't retrieve data with a DOI for some reason? I guess the landing page card just won't have the publication link? Would that be ok?
* How thorough Crossref's indexing is, if it's something we need to worry about.
