### ISSUE TITLE
Trajectory converter should give public access to data as json

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/simulariumio#45]
## Use Case

I am using the similiarumio in a lambda function, and instead of writing out to a file, I want to just return the json. But currently the only public method is `writeJSON` which needs a file path

## Acceptance Criteria

I should be able to do CustomConverter(converted_data).toJSON() which would return `_data` as a JSON
currently i'm doing this 
```
    data = CustomConverter(converted_data)._data
    return json.dumps(data)
```

## Details

_Please provide any helpful specifications_

**Comment by blairlyons** [comment]
with the new version (to be released soon!), `TrajectoryConverter._data` is a `TrajectoryData` object and it has to be changed into buffer form before being turned to json:
`
converter = TrajectoryConverter(input_data)
buffer_data = converter._read_trajectory_data(converter._data)
json.dumps(buffer_data)
`
agreed we should add a public function for this.
